/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.controller;

/**
 *
 * @author devel
 */
public class ui_06 extends javax.swing.JFrame {

    /**
     * Creates new form ui_2
     */
    controller c;
    public ui_06(controller c) {
        initComponents();
        this.c = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_salir = new javax.swing.JButton();
        b_consultar = new javax.swing.JButton();
        b_retirar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1200, 700));

        b_salir.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        b_salir.setText("Salir");
        b_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_salirMouseClicked(evt);
            }
        });

        b_consultar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        b_consultar.setText("Consultar saldo");
        b_consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_consultarMouseClicked(evt);
            }
        });

        b_retirar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        b_retirar.setText("Retirar saldo");
        b_retirar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_retirarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(b_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 377, Short.MAX_VALUE)
                .addComponent(b_retirar, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(404, 404, 404)
                .addComponent(b_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_retirar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(b_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_salirMouseClicked
        // TODO add your handling code here:
        c.UsuarioDecideSalir();
        dispose();
    }//GEN-LAST:event_b_salirMouseClicked

    private void b_consultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_consultarMouseClicked
        c.UsuarioConsultaSaldo();
        dispose();
    }//GEN-LAST:event_b_consultarMouseClicked

    private void b_retirarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_retirarMouseClicked
        c.UsuarioDeseaRetirar();
        dispose();
    }//GEN-LAST:event_b_retirarMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_consultar;
    private javax.swing.JButton b_retirar;
    private javax.swing.JButton b_salir;
    // End of variables declaration//GEN-END:variables
}
