/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.controller;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Ruuubs
 */
public class ui_09 extends javax.swing.JFrame {

    controller c;
    String input ="";
    int cant;

    public ui_09(controller c) {
        initComponents();
        this.c = c;
    }

    
    public void actualiza(){
        this.t_cant.setText(this.input);
    }
    
    public void limpia(){
        input = "";
        actualiza();;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        b_corregir = new javax.swing.JButton();
        b_num_1 = new javax.swing.JButton();
        b_num_2 = new javax.swing.JButton();
        b_num_3 = new javax.swing.JButton();
        b_num_4 = new javax.swing.JButton();
        b_num_6 = new javax.swing.JButton();
        b_num_5 = new javax.swing.JButton();
        b_num_7 = new javax.swing.JButton();
        b_num_9 = new javax.swing.JButton();
        b_num_8 = new javax.swing.JButton();
        b_char_1 = new javax.swing.JButton();
        b_char_2 = new javax.swing.JButton();
        b_num_0 = new javax.swing.JButton();
        b_confirmar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        t_cant = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1200, 700));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel1.setText("Ingrese la cantidad");

        b_corregir.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        b_corregir.setText("Corregir");
        b_corregir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_corregirMouseClicked(evt);
            }
        });

        b_num_1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        b_num_1.setText("1");
        b_num_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_num_1MouseClicked(evt);
            }
        });

        b_num_2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        b_num_2.setText("2");
        b_num_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_num_2MouseClicked(evt);
            }
        });

        b_num_3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        b_num_3.setText("3");
        b_num_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_num_3MouseClicked(evt);
            }
        });

        b_num_4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        b_num_4.setText("4");
        b_num_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_num_4MouseClicked(evt);
            }
        });

        b_num_6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        b_num_6.setText("6");
        b_num_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_num_6MouseClicked(evt);
            }
        });

        b_num_5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        b_num_5.setText("5");
        b_num_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_num_5MouseClicked(evt);
            }
        });

        b_num_7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        b_num_7.setText("7");
        b_num_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_num_7MouseClicked(evt);
            }
        });

        b_num_9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        b_num_9.setText("9");
        b_num_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_num_9MouseClicked(evt);
            }
        });

        b_num_8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        b_num_8.setText("8");
        b_num_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_num_8MouseClicked(evt);
            }
        });

        b_char_1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        b_char_1.setText("*");

        b_char_2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        b_char_2.setText("#");

        b_num_0.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        b_num_0.setText("0");
        b_num_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_num_0MouseClicked(evt);
            }
        });

        b_confirmar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        b_confirmar.setText("Confirmar");
        b_confirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_confirmarMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel2.setText("Solo multiplos de 50.");

        t_cant.setEditable(false);
        t_cant.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_cant, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(b_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b_num_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b_num_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b_num_4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b_num_5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_num_6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_num_3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b_num_7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b_num_8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b_char_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b_num_0, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_char_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_num_9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(b_corregir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b_corregir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(b_num_1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b_num_2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b_num_3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(b_num_4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b_num_6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b_num_5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(b_num_7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b_num_9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b_num_8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(b_char_1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b_char_2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b_num_0, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(98, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(b_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(t_cant, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_num_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_num_1MouseClicked
        // TODO add your handling code here:
        this.input+= 1;
        actualiza();
    }//GEN-LAST:event_b_num_1MouseClicked

    private void b_num_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_num_2MouseClicked
        // TODO add your handling code here:
        this.input+= 2;
        actualiza();
    }//GEN-LAST:event_b_num_2MouseClicked

    private void b_num_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_num_3MouseClicked
        // TODO add your handling code here:
        this.input+= 3;
        actualiza();
    }//GEN-LAST:event_b_num_3MouseClicked

    private void b_num_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_num_4MouseClicked
        // TODO add your handling code here:}
        this.input+= 4;
        actualiza();
    }//GEN-LAST:event_b_num_4MouseClicked

    private void b_num_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_num_5MouseClicked
        // TODO add your handling code here:
        this.input+= 5;
        actualiza();
    }//GEN-LAST:event_b_num_5MouseClicked

    private void b_num_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_num_6MouseClicked
        // TODO add your handling code here:
        this.input+= 6;
        actualiza();
    }//GEN-LAST:event_b_num_6MouseClicked

    private void b_num_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_num_7MouseClicked
        // TODO add your handling code here:
        this.input+= 7;
        actualiza();
    }//GEN-LAST:event_b_num_7MouseClicked

    private void b_num_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_num_8MouseClicked
        // TODO add your handling code here:
        this.input+= 8;
        actualiza();
    }//GEN-LAST:event_b_num_8MouseClicked

    private void b_num_9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_num_9MouseClicked
        // TODO add your handling code here:
        this.input+= 9;
        actualiza();
    }//GEN-LAST:event_b_num_9MouseClicked

    private void b_num_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_num_0MouseClicked
        // TODO add your handling code here:
        this.input+= 0;
        actualiza();
    }//GEN-LAST:event_b_num_0MouseClicked

    private void b_corregirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_corregirMouseClicked
        // TODO add your handling code here:
        limpia();
    }//GEN-LAST:event_b_corregirMouseClicked

    private void b_confirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_confirmarMouseClicked
        // TODO add your handling code here:
        c.UsuarioConfirmaMensaje();
        dispose();
    }//GEN-LAST:event_b_confirmarMouseClicked

    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_char_1;
    private javax.swing.JButton b_char_2;
    private javax.swing.JButton b_confirmar;
    private javax.swing.JButton b_corregir;
    private javax.swing.JButton b_num_0;
    private javax.swing.JButton b_num_1;
    private javax.swing.JButton b_num_2;
    private javax.swing.JButton b_num_3;
    private javax.swing.JButton b_num_4;
    private javax.swing.JButton b_num_5;
    private javax.swing.JButton b_num_6;
    private javax.swing.JButton b_num_7;
    private javax.swing.JButton b_num_8;
    private javax.swing.JButton b_num_9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JFormattedTextField t_cant;
    // End of variables declaration//GEN-END:variables
}
